# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: renforce.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0erenforce.proto"%\n\tTimestamp\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\n\n\x02us\x18\x02 \x01(\r"G\n\tEcgBuffer\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05lodpn\x18\x02 \x01(\x05\x12\x1d\n\ttimestamp\x18\x03 \x01(\x0b\x32\n.Timestamp"\'\n\tImpedance\x12\x0c\n\x04real\x18\x01 \x01(\x02\x12\x0c\n\x04imag\x18\x02 \x01(\x02"D\n\tEdaBuffer\x12\x18\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\n.Impedance\x12\x1d\n\ttimestamp\x18\x02 \x01(\x0b\x32\n.Timestampb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "renforce_pb2", globals())
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    _TIMESTAMP._serialized_start = 18
    _TIMESTAMP._serialized_end = 55
    _ECGBUFFER._serialized_start = 57
    _ECGBUFFER._serialized_end = 128
    _IMPEDANCE._serialized_start = 130
    _IMPEDANCE._serialized_end = 169
    _EDABUFFER._serialized_start = 171
    _EDABUFFER._serialized_end = 239
# @@protoc_insertion_point(module_scope)
